lib/ethermass_web/router.ex
defmodule EthermassWeb.Router do
  use EthermassWeb, :router

  import EthermassWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {EthermassWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", EthermassWeb do
    pipe_through :browser

  end

  # Other scopes may use custom stacks.
  # scope "/api", EthermassWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: EthermassWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", EthermassWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", EthermassWeb do
    pipe_through [:browser, :require_authenticated_user]


    get "/", PageController, :index
    get "/addresses/:address/refresh_balance", AddressController, :refresh_eth_balance
    get "/addresses/generate", AddressController, :generate_form
    post "/addresses/generate", AddressController, :generate_post

    resources "/owner_list", OwnerListController
    resources "/market_maker", MarketMakerController

    get "/all_nft", PageController, :all_nft

    get "/addresses/batch_import", AddressController, :batch_import_form
    post "/addresses/batch_import", AddressController, :batch_import_post

    get "/address/update_nft_balance/:id", AddressController, :update_nft_balance
    get "/address/update_eth_balance/:id", AddressController, :update_eth_balance
    resources "/addresses", AddressController

    get "/transaction_batch/:id/toggle", TransactionBatchController, :toggle_start
    resources "/transaction_batch", TransactionBatchController

    get "/transaction_batch/mass_funding/new", TransactionBatchController, :new_mass_funding
    post "/transaction_batch/mass_funding", TransactionBatchController, :create_mass_funding
    get "/transaction_batch/mass_minting/new", TransactionBatchController, :new_mass_minting
    post "/transaction_batch/mass_minting", TransactionBatchController, :create_mass_minting
    get "/transaction_batch/mass_whitelist/new", TransactionBatchController, :new_mass_whitelist
    post "/transaction_batch/mass_whitelist", TransactionBatchController, :create_mass_whitelist

    get "/transaction_plan/:id/run", TransactionPlanController, :run_plan

    resources "/transaction_plans", TransactionPlanController

    resources "/smart_contracts", SmartContractController

    get "/test", PageController, :test
    get "/mass_funding_index", PageController, :mass_funding_index





    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", EthermassWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/ethermass/transaction/transaction_batch.ex
defmodule Ethermass.Transaction.TransactionBatch do
  use Ecto.Schema
  import Ecto.Changeset
  alias Ethermass.Transaction

  schema "transaction_batch" do
    field :gas_limit, :integer
    field :gas_price, :integer
    field :network, :string
    field :status, :string, default: "unstarted"
    field :title, :string
    field :to, :string
    field :type, :string
    field :value, :float
    field :csv_source, :string, virtual: true
    field :minting_cost, :float, virtual: true

    timestamps()

    has_many :transaction_plan, Ethermass.Transaction.TransactionPlan
  end

  @spec changeset(
          {map, map}
          | %{
              :__struct__ => atom | %{:__changeset__ => map, optional(any) => any},
              optional(atom) => any
            },
          :invalid | %{optional(:__struct__) => none, optional(atom | binary) => any}
        ) :: Ecto.Changeset.t()
  @doc false
  def changeset(transaction_batch, attrs) do
    transaction_batch
    |> cast(attrs, [:title, :csv_source, :type, :status, :to, :gas_price, :gas_limit, :network, :value])
    |> validate_required([:title, :type, :gas_price, :gas_limit, :network])
  end

  def changeset_mass_funding(transaction_batch, attrs) do
    transaction_batch
    |> cast(attrs, [:title, :csv_source, :type, :status, :to, :gas_price, :gas_limit, :network, :value])
    |> put_change(:type, "eth_transfer")
    |> put_change(:network, Ethermass.get_network())
    |> validate_required([:title, :gas_price, :gas_limit, :csv_source ])
    |> validate_mass_funding_csv_source()
  end

  def changeset_mass_whitelisting(transaction_batch, attrs) do
    transaction_batch
    |> cast(attrs, [:title, :csv_source, :type, :status, :to, :gas_price, :gas_limit, :network, :value])
    |> put_change(:type, "nft_whitelisting")
    |> put_change(:network, Ethermass.get_network())
    |> validate_required([:title, :gas_price, :gas_limit, :csv_source ])
    |> validate_mass_whitelisting_csv_source()
  end

  def changeset_mass_minting(transaction_batch, attrs) do
    transaction_batch
    |> cast(attrs, [:title, :csv_source, :to, :gas_price, :gas_limit, :minting_cost])
    |> put_change(:type, "nft_minting")
    |> put_change(:network, Ethermass.get_network())
    |> validate_required([:title, :gas_price, :to, :gas_limit, :csv_source, :minting_cost])
    |> validate_mass_minting_csv_source()
  end

  def validate_mass_funding_csv_source(changeset) do
    csv_file = get_field(changeset, :csv_source)

    if is_nil(csv_file) do
      changeset
    else
      case Transaction.validate_csv_mass_funding(csv_file) do
        {:ok, _} -> changeset
        {:error, reason} -> add_error(changeset, :csv_source, reason)
      end
    end
  end

  def validate_mass_whitelisting_csv_source(changeset) do
    csv_file = get_field(changeset, :csv_source)

    if is_nil(csv_file) do
      changeset
    else
      case Transaction.validate_csv_mass_whitelist(csv_file) do
        {:ok, _} -> changeset
        {:error, reason} -> add_error(changeset, :csv_source, reason)
      end
    end
  end

  def validate_mass_minting_csv_source(changeset) do
    csv_file = get_field(changeset, :csv_source)

    if is_nil(csv_file) do
      changeset
    else
      case Transaction.validate_csv_mass_minting(csv_file) do
        {:ok, _} -> changeset
        {:error, reason} -> add_error(changeset, :csv_source, reason)
      end
    end
  end
end

lib/ethermass_web/controllers/transaction_batch_controller.ex
defmodule EthermassWeb.TransactionBatchController do
  use EthermassWeb, :controller

  alias Ethermass.Transaction
  alias Ethermass.Transaction.TransactionBatch

  def index(conn, _params) do
    transaction_batch = Transaction.list_transaction_batch()
    render(conn, "index.html", transaction_batch: transaction_batch)
  end

  def toggle_start(conn, %{"id" => id}) do
    transaction_batch = Transaction.get_transaction_batch!(id)

    case Transaction.toggle_transaction_batch(transaction_batch) do
      {:ok, _transaction_batch} ->
        transaction_batch = Transaction.list_transaction_batch()
        render(conn, "index.html", transaction_batch: transaction_batch)

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", transaction_batch: transaction_batch, changeset: changeset)

      {:error, reason} ->
        transaction_batch = Transaction.list_transaction_batch()

          conn
          |> put_flash(:error, reason)
          |> render("index.html", transaction_batch: transaction_batch)
    end
  end

  def new(conn, _params) do
    changeset = Transaction.change_transaction_batch(%TransactionBatch{})
    render(conn, "new.html", changeset: changeset)
  end

  def new_mass_funding(conn, _params) do
    changeset = Transaction.change_transaction_batch(%TransactionBatch{})
    render(conn, "new_mass_funding.html", changeset: changeset)
  end

  def new_mass_whitelist(conn, _params) do
    changeset = Transaction.change_transaction_batch(%TransactionBatch{})
    render(conn, "new_mass_whitelist.html", changeset: changeset)
  end

  def create_mass_whitelist(conn, %{"transaction_batch" => transaction_batch_params}) do
    IO.inspect(transaction_batch_params)
    case Transaction.create_transaction_batch_mass_whitelist(transaction_batch_params) do
      {:ok, _transaction_batch} ->
        conn
        |> put_flash(:info, "Transaction batch created successfully.")
        |> redirect(to: Routes.transaction_batch_path(conn, :index))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new_mass_whitelist.html", changeset: changeset)

      {:error, :transaction_batch, %Ecto.Changeset{} = changeset, _} ->
          render(conn, "new_mass_whitelist.html", changeset: changeset)
      error ->
          IO.inspect(error)
        text(conn, "Error. Check console.")
    end
  end

  def create_mass_funding(conn, %{"transaction_batch" => transaction_batch_params}) do
    IO.inspect(transaction_batch_params)
    case Transaction.create_transaction_batch_mass_funding(transaction_batch_params) do
      {:ok, _transaction_batch} ->
        conn
        |> put_flash(:info, "Transaction batch created successfully.")
        |> redirect(to: Routes.transaction_batch_path(conn, :index))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new_mass_funding.html", changeset: changeset)

      {:error, :transaction_batch, %Ecto.Changeset{} = changeset, _} ->
          render(conn, "new_mass_funding.html", changeset: changeset)
      error ->
          IO.inspect(error)
        text(conn, "Error. Check console.")
    end
  end


  def new_mass_minting(conn, _params) do
    changeset = Transaction.change_transaction_batch(%TransactionBatch{})
    render(conn, "new_mass_minting.html", changeset: changeset)
  end


  def create_mass_minting(conn, %{"transaction_batch" => transaction_batch_params}) do
    case Transaction.create_transaction_batch_mass_minting(transaction_batch_params) do
      {:ok, _transaction_batch} ->
        conn
        |> put_flash(:info, "Transaction batch created successfully.")
        |> redirect(to: Routes.transaction_batch_path(conn, :index))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new_mass_minting.html", changeset: changeset)

      {:error, :transaction_batch, %Ecto.Changeset{} = changeset, _} ->
          render(conn, "new_mass_minting.html", changeset: changeset)
      error ->
        text(conn, "Error. Check console.")
    end
  end


  def create(conn, %{"transaction_batch" => transaction_batch_params}) do
    case Transaction.create_transaction_batch(transaction_batch_params) do
      {:ok, transaction_batch} ->
        conn
        |> put_flash(:info, "Transaction batch created successfully.")
        |> redirect(to: Routes.transaction_batch_path(conn, :show, transaction_batch))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    transaction_batch = Transaction.get_transaction_batch!(id)

    summary = Ethermass.Transaction.get_status_summary(transaction_batch.id)

    case transaction_batch.type do
      "nft_whitelisting" ->
        render(conn, "show_batch_whitelist.html", transaction_batch: transaction_batch, summary: summary)
      _other -> render(conn, "show.html", transaction_batch: transaction_batch)
    end


  end

  def edit(conn, %{"id" => id}) do
    transaction_batch = Transaction.get_transaction_batch!(id)
    changeset = Transaction.change_transaction_batch(transaction_batch)
    render(conn, "edit.html", transaction_batch: transaction_batch, changeset: changeset)
  end

  def update(conn, %{"id" => id, "transaction_batch" => transaction_batch_params}) do
    transaction_batch = Transaction.get_transaction_batch!(id)

    case Transaction.update_transaction_batch(transaction_batch, transaction_batch_params) do
      {:ok, transaction_batch} ->
        conn
        |> put_flash(:info, "Transaction batch updated successfully.")
        |> redirect(to: Routes.transaction_batch_path(conn, :show, transaction_batch))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", transaction_batch: transaction_batch, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    transaction_batch = Transaction.get_transaction_batch!(id)
    {:ok, _transaction_batch} = Transaction.delete_transaction_batch(transaction_batch)

    conn
    |> put_flash(:info, "Transaction batch deleted successfully.")
    |> redirect(to: Routes.transaction_batch_path(conn, :index))
  end
end

lib/ethermass_web/views/transaction_batch_view.ex
defmodule EthermassWeb.TransactionBatchView do
  use EthermassWeb, :view

  def truncate_address(address) do
    String.slice(address, 0,6) <> "..." <> String.slice(address, -4, 4)
  end

  def get_target_address(arguments) do
    arguments |> String.split(",") |> List.first() |> String.replace("[", "")
  end
end

lib/ethermass_web/templates/transaction_batch/edit.html.heex
<h1>Edit Transaction batch</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.transaction_batch_path(@conn, :update, @transaction_batch)) %>

<span><%= link "Back", to: Routes.transaction_batch_path(@conn, :index) %></span>

lib/ethermass_web/templates/transaction_batch/form.html.heex
<.form let={f} for={@changeset} action={@action}>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :title %>
  <%= text_input f, :title %>
  <%= error_tag f, :title %>

  <%= label f, :network %>
  <%= select f, :network, [{"Rinkeby", "rinkeby"}, {"Mainnet", "mainnet"}] %>
  <%= error_tag f, :network %>  

  <%= label f, :type %>
  <%= select f, :type, ["NFT mint", "ERC20 transfer", "ETH transfer"] %>
  <%= error_tag f, :type %>

  <%= label f, "Gas Price (GWEI)" %>
  <%= number_input f, :gas_price %>
  <%= error_tag f, :gas_price %>

  <%= label f, "gas limit (unit)" %>
  <%= number_input f, :gas_limit %>
  <%= error_tag f, :gas_limit %>

  <%= label f, :status %>
  <%= select f, :status, [{"Unstarted", "unstarted"}, {"In Progress", "in_progress"}, {"Paused", "paused"}] %>
  <%= error_tag f, :gas_limit %>  

  <div>
    <%= submit "Save" %>
  </div>
</.form>

lib/ethermass_web/templates/transaction_batch/form_mass_funding.html.heex
<.form let={f} for={@changeset} action={@action}>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :title %>
  <%= text_input f, :title %>
  <%= error_tag f, :title %>

  <%= label f, "Gas Price (GWEI)" %>
  <%= number_input f, :gas_price %>
  <%= error_tag f, :gas_price %>

  <%= label f, "gas limit (unit)" %>
  <%= number_input f, :gas_limit %>
  <%= error_tag f, :gas_limit %>

  <%= label f, :csv_source %>
  <%= text_input f, :csv_source %>
  <%= error_tag f, :csv_source %>

  <div>
    <%= submit "Save" %>
  </div>
</.form>

lib/ethermass_web/templates/transaction_batch/new.html.heex
<h1>New Transaction batch</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.transaction_batch_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.transaction_batch_path(@conn, :index) %></span>

lib/ethermass_web/templates/transaction_batch/new_mass_funding.html.heex
<h1>New Transaction Batch Mass Funding</h1>

<%= render "form_mass_funding.html", Map.put(assigns, :action, Routes.transaction_batch_path(@conn, :create_mass_funding)) %>

<span><%= link "Back", to: Routes.transaction_batch_path(@conn, :index) %></span>

lib/ethermass_web/templates/transaction_batch/show.html.heex
<h1>Transaction Batch Detail</h1>

<ul>

  <li>
    <strong>ID:</strong>
    <%= @transaction_batch.id %>
  </li>

  <li>
    <strong>Title:</strong>
    <%= @transaction_batch.title %>
  </li>

  <li>
    <strong>Type:</strong>
    <%= @transaction_batch.type %>
  </li>

  <li>
    <strong>Gas price:</strong>
    <%= @transaction_batch.gas_price %>
  </li>

  <li>
    <strong>Gas limit:</strong>
    <%= @transaction_batch.gas_limit %>
  </li>

  <li>
    <strong>Network:</strong>
    <%= @transaction_batch.network %>
  </li>

  <li>
    <strong>Created At:</strong>
    <%= @transaction_batch.inserted_at %>
  </li>

  <li>
    <strong>Status:</strong>
    <%= @transaction_batch.status %>
  </li>


</ul>

<span><%= link "Edit", to: Routes.transaction_batch_path(@conn, :edit, @transaction_batch) %></span> |
<span><%= link "Back", to: Routes.transaction_batch_path(@conn, :index) %></span>

<div style="margin-top: 100px;"></div>

<h2>Transaction Plans</h2>

<table>
  <thead>
    <tr>
      <th>Action</th>
      <th>ID</th>
      <th>From</th>
      <th>To</th>
      <th>Value</th>
      <th>Hash</th>
      <th>Status</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for transaction_plan <- @transaction_batch.transaction_plan do %>
    <tr>
      <td>

        <%= if transaction_plan.status == "in_progress" do %>
          <a class="share-dialog" href="" title="Start The Process"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-pause"><rect x="6" y="4" width="4" height="16"></rect><rect x="14" y="4" width="4" height="16"></rect></svg></a>
        <% end %>

          <%= if transaction_plan.status == "finished" do %>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="teal" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-check"><polyline points="20 6 9 17 4 12"></polyline></svg>
          <% end %>


          <%= if transaction_plan.status == "unstarted" do %>
            <a class="share-dialog" href={"/transaction_plan/#{transaction_plan.id}/run"} title="Start The Process"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-play"><polygon points="5 3 19 12 5 21 5 3"></polygon></svg></a>
          <% end %>




      </td>
      <td><%= transaction_plan.id %></td>
      <td>
          <%= link truncate_address(transaction_plan.from), to: Ethermass.get_explorer_link(transaction_plan.from), target: "_blank" %>

      </td>
      <td><%= truncate_address(transaction_plan.to) %></td>
      <td><%= transaction_plan.value |> :erlang.float_to_binary([:compact, { :decimals, 20 }]) %></td>
      <td>

      <%= link transaction_plan.hash, to: Ethermass.get_explorer_link(transaction_plan.hash, "tx"), target: "_blank" %>

      </td>
      <td><%= transaction_plan.status %></td>

      <td>
        <span><%= link "Show", to: Routes.transaction_plan_path(@conn, :show, transaction_plan) %></span>
        <span><%# link "Edit", to: Routes.transaction_plan_path(@conn, :edit, transaction_plan) %></span>
        <span><%= link "Delete", to: Routes.transaction_plan_path(@conn, :delete, transaction_plan), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%# link "New Transaction plan", to: Routes.transaction_plan_path(@conn, :new) %></span>

lib/ethermass_web/templates/transaction_batch/show_batch_whitelist.html.heex
<style>

.card {
    border-radius: .4rem;
    display: block;
    letter-spacing: .1rem;
    line-height: 3rem;
    margin-bottom: 2.5rem;
    text-align: center;
    padding: 1rem;
    color: white;
}

.card-number-big {
  font-size: 2rem;
  font-weight: 700;
}


</style>

<h1>Transaction Batch Whitelisting Detail</h1>

<ul>

  <li>
    <strong>ID:</strong>
    <%= @transaction_batch.id %>
  </li>

  <li>
    <strong>Title:</strong>
    <%= @transaction_batch.title %>
  </li>

  <li>
    <strong>Type:</strong>
    <%= @transaction_batch.type %>
  </li>

  <li>
    <strong>Gas price:</strong>
    <%= @transaction_batch.gas_price %>
  </li>

  <li>
    <strong>Gas limit:</strong>
    <%= @transaction_batch.gas_limit %>
  </li>

  <li>
    <strong>Network:</strong>
    <%= @transaction_batch.network %>
  </li>

  <li>
    <strong>Created At:</strong>
    <%= @transaction_batch.inserted_at %>
  </li>

  <li>
    <strong>Status:</strong>
    <%= @transaction_batch.status %>
  </li>


</ul>

<span><%= link "Edit", to: Routes.transaction_batch_path(@conn, :edit, @transaction_batch) %></span> |
<span><%= link "Back", to: Routes.transaction_batch_path(@conn, :index) %></span>

<div style="margin-top: 100px;"></div>

  <h2>Stats</h2>
  <div class="row">
    <div class="column">
      <div class="card" style="background: #264653;">
        <div>Total</div>
        <div><%=  @summary.total %></div>
      </div>
    </div>
    <div class="column">
      <div class="card" style="background: #2a9d8f;">
        <div>Success</div>
        <div><%= @summary.success  %></div>
      </div>
    </div>
    <div class="column">
      <div class="card" style="background: #e9c46a;">
        <div>Unstarted </div>
        <div><%= @summary.unstarted %></div>
      </div>
    </div>  
    <div class="column">
      <div class="card" style="background: #e9c46a;">
        <div>Pending</div>
        <div><%= @summary.wait_confirmation%></div>
      </div>
    </div> 
    <div class="column">
      <div class="card" style="background: #e9c46a;">
        <div>Not found</div>
        <div><%= @summary.undefined %></div>
      </div>
    </div>          
    <div class="column">
      <div class="card" style="background: #e9c46a;">
        <div>Postponed </div>
        <div><%= @summary.postponed %></div>
      </div>
    </div>       
    <div class="column">
      <div class="card" style="background: #f4a261;">
        <div>Failed</div>
        <div><%= @summary.failed_with_tx + @summary.failed_without_tx %></div>
      </div>
    </div>                  
  </div>


<div style="margin-top: 100px;"></div>

<h2>Transaction Plans</h2>

<table>
  <thead>
    <tr>
      <th>Action</th>  
      <th>ID</th>
      <th>Gas Price</th>
      <th>Whitelist Address</th>
      <th>Target</th>
      <th>Actual</th>
      <th>Hash</th>
      <th>Status</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for transaction_plan <- @transaction_batch.transaction_plan do %>
    <tr>
      <td>
        


        <%= if Enum.member?(["unstarted", "failed", "postponed"], transaction_plan.status) do %>
            <a class="share-dialog" href={"/transaction_plan/#{transaction_plan.id}/run"} title="Start The Process"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-play"><polygon points="5 3 19 12 5 21 5 3"></polygon></svg></a>  
        <% end %>  

        <%= if transaction_plan.status == "success" do %>
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="teal" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-check"><polyline points="20 6 9 17 4 12"></polyline></svg>
        <% end %>



        <%= if transaction_plan.status == "wait_confirmation" do %>

          <a class="share-dialog" href={"/transaction_plan/#{transaction_plan.id}/get_status"} title="Start The Process"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-refresh-cw"><polyline points="23 4 23 10 17 10"></polyline><polyline points="1 20 1 14 7 14"></polyline><path d="M3.51 9a9 9 0 0 1 14.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0 0 20.49 15"></path></svg></a>

        <% end %>        


      </td>    
      <td><%= transaction_plan.id %></td> 
      <td><%= transaction_plan.gas_price %></td>   
      <td>
          <div> <%= link get_target_address(transaction_plan.arguments), to: Ethermass.get_explorer_link(get_target_address(transaction_plan.arguments)), target: "_blank" %> </div>
          
      </td>
      <td><%= transaction_plan.whitelist_count || "n/a" %></td>
      <td><%= transaction_plan.nft_balance || "n/a" %></td>
      <td>
      
      <%= link transaction_plan.hash, to: Ethermass.get_explorer_link(transaction_plan.hash, "tx"), target: "_blank" %>
      
      </td>
      <td><%= transaction_plan.status %></td>

      <td>
        <span><%= link "Show", to: Routes.transaction_plan_path(@conn, :show, transaction_plan) %></span>
        <span><%# link "Edit", to: Routes.transaction_plan_path(@conn, :edit, transaction_plan) %></span>
        <span><%# link "Delete", to: Routes.transaction_plan_path(@conn, :delete, transaction_plan), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%# link "New Transaction plan", to: Routes.transaction_plan_path(@conn, :new) %></span>